image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint

tasks:
  - name: Install dependencies
    command: npm install

  - name: Build
    command: npm run build

ports:
  - port: 3000
    onOpen: open-preview
